### ISSUE TITLE
Broken link from Zfinx_spec.adoc

### ISSUE THREAD

**Issue by anderslindgren-iar** [riscvarchive/riscv-zfinx#16]
The header of the file Zfinx_spec.adoc contains the text "[DEPRECATED - SEE THIS DOCUMENT INSTEAD](https://github.com/riscv/riscv-zfinx/blob/master/zfinx-spec-20210511-0.41.pdf)".

Unfortunately, the pdf it refers to doesn't exist.

**Comment by tariqkurd-repo** [comment]
fixed, thanks for reporting
